function [ph, slh, pbh, edh] = play(parent, data, position)
%[slh,pbh,edh]=PLAY(parent,data) make slider panel for frame number & Play button
%   parent: parent figure/uipanel
%   data: object that carries GUI state (subclass of handle)
%   varname: name of property of DATA to update.
%
%   Makes its own panel.
%   DATA must have properties {frameno,firstfr,lastfr,play,opts_pnl,opts_btn}
%   and methods {Play}.

ph = uipanel(parent, data.opts_pnl{:},...
    'Position', position, 'Title', 'Frame');
%slider
slh = uicontrol(ph, 'Style', 'slider', data.opts_btn{:},...
    'Max', data.lastfr, 'Min', data.firstfr,...
    'Value', data.frameno,...
    'SliderStep', [1 10]/(data.lastfr - data.firstfr),...
    'Position', [0.1 0.25 0.8 0.7],...
    'DeleteFcn', @mygui.helpers.circDeleteFcn,...
    'Callback', {@mygui.callback.sl, data, 'frameno',...
        matlab.ui.control.UIControl.empty, @floor});
%Play button
pbh = uicontrol(ph, 'Style', 'pushbutton', data.opts_btn{:},...
    'String', 'Play',...
    'Position', [0.0 0.25 0.1 0.7],...
    'DeleteFcn', @mygui.helpers.circDeleteFcn,...
    'Callback', {@mygui.callback.play, data});
%display frame number
edh = uicontrol(ph, 'Style', 'edit', data.opts_btn{:},...
    'String', num2str(data.frameno),...
    'Position', [0.9 0.25 0.1 0.7],...
    'DeleteFcn', @mygui.helpers.circDeleteFcn,...
    'Callback', {@mygui.callback.sled, slh});
slh.Callback{4} = edh;  %circular references!
%slider labels
uicontrol(ph, 'Style', 'text', data.opts_btn{:},...
    'String', data.firstfr,...
    'Position', [0.1 0.05 0.08 0.2]);
uicontrol(ph, 'Style', 'text', data.opts_btn{:},...
    'String', data.lastfr,...
    'Position', [0.85 0.05 0.05 0.2]);

end%function MakeSliderPlay
