function [slh, edh] = slider(parent, data, varname, minval, maxval, varargin)
%[slh,edh]=SLIDER(parent,data,varname,minval,maxval,slpos) make slider panel
%   parent: parent figure/uipanel
%   data: object that carries GUI state (subclass of handle)
%   varname: name of property of DATA to update.
%   minval, maxval: range of DATA.VARNAME
%   DATA must have a method called Update with signature Update(OBJ,SRC)

if isempty(parent.Title)
    parent.Title = varname;
end
midval = data.(varname);
%slider
slh = uicontrol(parent, 'Style', 'slider', varargin{:},...
    'Max', maxval, 'Min', minval, 'Value', midval,...
    'SliderStep', [0.05 0.1],...
    'Position', [0.1 0.25 0.8 0.7],...
    'Callback', {@mygui.callback.sl, data, varname,...
        matlab.ui.control.UIControl.empty},...
    'DeleteFcn', @mygui.circDeleteFcn);
%button to set slider to middle value
uicontrol(parent, 'Style', 'pushbutton', varargin{:},...
    'String', num2str(midval),...
    'Position', [0.0 0.25 0.1 0.7],...
    'Callback', {@mygui.callback.slpb, slh, midval});
%display value of slider
edh = uicontrol(parent, 'Style', 'edit', varargin{:},...
    'String', num2str(slh.Value),...
    'Position', [0.9 0.25 0.1 0.7],...
    'Callback', {@mygui.callback.sled, slh},...
    'DeleteFcn', @mygui.circDeleteFcn);
slh.Callback{3} = edh;  %circular references!
%slider labels
uicontrol(parent, 'Style', 'text', varargin{:},...
    'String', num2str(minval),...
    'Position', [0.1 0.05 0.08 0.2]);
uicontrol(parent, 'Style', 'text', varargin{:},...
    'String', num2str(midval),...
    'Position', [0.1+0.8*(midval-minval)/(maxval-minval) 0.05 0.05 0.2]);
uicontrol(parent, 'Style', 'text', varargin{:},...
    'String', num2str(maxval),...
    'Position', [0.85 0.05 0.05 0.2]);

end%function MakeSlider
